apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: python-app
  template:  
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: gcr.io/fabled-zone-375709/final-task
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: final-task-config-map
        